Update Greet

diff --git a/Greet b/Greet
--- a/Greet
+++ b/Greet
@@ -32,20 +32,20 @@ then
  
  if [ $# -eq 0 ]
 then
-	echo "Please enter at least one user to greet."
-    exit 1
+     echo "Please enter at least one user to greet."
+     exit 1
 else
-	for username in $@
-	do
-		echo $username | grep "^[A-Za-z]*$" > /dev/null
-		if [ $? -eq 1 ]
-		then
-			echo "ERROR: Names must only contains letters."
-			exit 2
-		else
-			echo "Hello $username!"
-		fi
-	done
-	exit 0
+     for username in $@
+     do
+	echo $username | grep "^[A-Za-z]*$" > /dev/null
+	if [ $? -eq 1 ]
+	then
+	     echo "ERROR: Names must only contains letters."
+	     exit 2
+	else
+	     echo "Hello $username!"
+	fi
+     done
+     exit 0
 fi
  
